//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DexterER2.Properties {

    using System;
    using System.CodeDom.Compiler;
    using System.Configuration;
    using System.Diagnostics;
    using System.IO.Ports;
    using System.Runtime.CompilerServices;

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        [DebuggerNonUserCode, DefaultSettingValue("9600"), UserScopedSetting]
        public int BaudRate
        {
            get
            {
                return (int)this["BaudRate"];
            }
            set
            {
                this["BaudRate"] = value;
            }
        }

        [UserScopedSetting, DefaultSettingValue("8"), DebuggerNonUserCode]
        public int DataBits
        {
            get
            {
                return (int)this["DataBits"];
            }
            set
            {
                this["DataBits"] = value;
            }
        }

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting, DefaultSettingValue("None"), DebuggerNonUserCode]
        public System.IO.Ports.Parity Parity
        {
            get
            {
                return (System.IO.Ports.Parity)this["Parity"];
            }
            set
            {
                this["Parity"] = value;
            }
        }

        [DefaultSettingValue("COM1"), UserScopedSetting, DebuggerNonUserCode]
        public string PortName
        {
            get
            {
                return (string)this["PortName"];
            }
            set
            {
                this["PortName"] = value;
            }
        }
    }
}
